#docker-composeのバージョン
version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '4306:3306' # ホストからゲストへポートフォワード
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root

    web:
      build: .
      command: rails s -p 3000 -b '0.0.0.0'
      # ローカルのディレクトリをマウント
      volumes:
        - .:/taxi_app
      ports:
        - "3000:3000"
      # appコンテナとdbコンテナを連携
      links:
        - db